baseURL = 'https://grcheulishvili.github.io/'
languageCode = 'en-us'
title = "user@cybrealm:~$"
theme = "hugo-xterm"


[params]
  description = "Security Engineer | MalDev | Go"
  prompt = "[user@cybrealm] ~ $ "
  centerTheme = true  # <--- ADD THIS LINE  
  # Social links (appear as 'contacts' or similar in terminal themes)
  # github = "grcheulishvili"
  # linkedin = "your-linkedin"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3

  [[menu.main]]
    name = "Engineering"
    url = "/engineering/"
    weight = 4

  [[menu.main]]
    name = "Whoami"
    url = "/about/"
    weight = 5

[params.terminal]
  # Color scheme settings often go here depending on the specific xterm fork
  # cursor = "_"
