baseURL = 'https://grcheulishvili.github.io/'
languageCode = 'en-us'
title = "Cybrealm"
theme = "hextra"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[params]
  description = "Security Engineer | MalDev | Go"
  
  # Corrected Theme Settings
  [params.theme]
    default = "dark"
    displayToggle = true

  [params.search]
    enable = true
    type = "flexsearch"

  [params.sidebar]
    enable = true
    autoCollapse = true

  [params.footer]
    enable = true
    displayCopyright = true

  [params.navbar]
    displayTitle = true
    displayLogo = false
